name: CI
on: [pull_request]
jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: lint
      uses: docker://devblackops/github-action-psscriptanalyzer:2.4.0
      with:
        settingsPath: .vscode/PSScriptAnalyzerSettings.psd1
        sendComment: false
        failOnInfos: true
        failOnErrors: true
        failOnWarnings: true
